import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

type PackageInfo = { path: string; name: string; scripts: string[] };

function packagesUnder(root: string): PackageInfo[] {
  return readdirSync(root, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .flatMap((entry) => {
      const path = join(root, entry.name);
      const manifest = join(path, 'package.json');
      try {
        const parsed = JSON.parse(readFileSync(manifest, 'utf8')) as {
          name?: string;
          scripts?: Record<string, string>;
        };
        if (!parsed.name) return [];
        return [
          {
            path: path.replaceAll('\\', '/'),
            name: parsed.name,
            scripts: Object.keys(parsed.scripts ?? {}).sort(),
          },
        ];
      } catch {
        return [];
      }
    });
}

const packages = [...packagesUnder('apps'), ...packagesUnder('packages')];
const edgeFunctions = readdirSync('supabase/functions', { withFileTypes: true })
  .filter((entry) => entry.isDirectory() && !entry.name.startsWith('_'))
  .map((entry) => entry.name)
  .sort();
const workflows = readdirSync('.github/workflows')
  .filter((entry) => /\.ya?ml$/i.test(entry))
  .sort();
const scripts = readdirSync('infrastructure/scripts')
  .filter((entry) => entry.endsWith('.ts'))
  .sort();
const lines = [
  '# Generated repository routing map',
  '',
  '> Generated by `corepack pnpm repo:map`. Use this as a routing index, not as product authority.',
  '',
  '## Workspaces',
  '',
  '| Path | Package | Available scripts |',
  '| --- | --- | --- |',
  ...packages.map(
    (item) =>
      `| \`${item.path}\` | \`${item.name}\` | ${item.scripts.map((script) => `\`${script}\``).join(', ')} |`,
  ),
  '',
  '## Stable ownership routes',
  '',
  '- Web/UI/API routes: `apps/web`',
  '- Shared contracts: `packages/contracts`',
  '- Agent orchestration/runtime: `packages/manager-core`, `packages/ai-runtime`',
  '- Database types/client: `packages/db`',
  '- Database schema/security: `supabase/migrations`, `supabase/tests`',
  '- Edge runtime: `supabase/functions`',
  '- Windows worker: `apps/windows-worker`',
  '- Delivery/QA/release: `infrastructure/scripts`, `.github/workflows`',
  '- Browser acceptance: `tests/e2e`, `tests/e2e-live`',
  '',
  `## Edge functions (${edgeFunctions.length})`,
  '',
  edgeFunctions.map((name) => `\`${name}\``).join(', '),
  '',
  `## Delivery workflows (${workflows.length})`,
  '',
  workflows.map((name) => `- \`.github/workflows/${name}\``).join('\n'),
  '',
  `## Infrastructure scripts (${scripts.length})`,
  '',
  scripts.map((name) => `- \`infrastructure/scripts/${name}\``).join('\n'),
  '',
];
mkdirSync('docs/engineering', { recursive: true });
writeFileSync('docs/engineering/repo-map.generated.md', lines.join('\n'), 'utf8');
process.stdout.write('Generated docs/engineering/repo-map.generated.md\n');
