-- Pass 06: Digital Estate, paired worker, archive and recovery contracts.
create table public.worker_devices (
 id uuid primary key default gen_random_uuid(), user_id uuid not null references public.app_users(id) on delete cascade, label text not null, public_key_b64 text not null unique, pairing_hash text unique, pairing_expires_at timestamptz, paired_at timestamptz, revoked_at timestamptz, last_heartbeat_at timestamptz, state text not null default 'pending' check(state in ('pending','paired','offline','online','revoked')), created_at timestamptz not null default now(), check((state='pending') = (paired_at is null))
);
create table public.worker_heartbeats (
 id uuid primary key default gen_random_uuid(), device_id uuid not null references public.worker_devices(id) on delete cascade, received_at timestamptz not null default now(), worker_version text, status jsonb not null default '{}'::jsonb
);
create table public.digital_scans (
 id uuid primary key default gen_random_uuid(), user_id uuid not null references public.app_users(id) on delete cascade, device_id uuid not null references public.worker_devices(id) on delete restrict, run_id uuid unique references public.workflow_runs(id), scan_kind text not null check(scan_kind in ('lightweight','deep')), approved_roots jsonb not null check(jsonb_typeof(approved_roots)='array'), status text not null default 'queued' check(status in ('queued','waiting_for_device','running','complete','cancelled','failed')), progress integer not null default 0 check(progress between 0 and 100), inventory_sha256 text, started_at timestamptz, completed_at timestamptz, created_at timestamptz not null default now()
);
create table public.digital_inventory_items (
 id uuid primary key default gen_random_uuid(), scan_id uuid not null references public.digital_scans(id) on delete cascade, user_id uuid not null references public.app_users(id) on delete cascade, path_token text not null, parent_token text, filename text not null, extension text, size_bytes bigint not null check(size_bytes>=0), modified_at timestamptz, sha256 text, mime_type text, git_state text, duplicate_group text, classification text not null default 'unclassified', created_at timestamptz not null default now(), unique(scan_id,path_token)
);
create table public.digital_findings (
 id uuid primary key default gen_random_uuid(), scan_id uuid not null references public.digital_scans(id) on delete cascade, user_id uuid not null references public.app_users(id) on delete cascade, category text not null check(category in ('clutter','duplicate','security','software','storage','backup')), severity public.risk_class not null, summary text not null, evidence jsonb not null default '[]'::jsonb, created_at timestamptz not null default now()
);
create table public.digital_plans (
 id uuid primary key default gen_random_uuid(), user_id uuid not null references public.app_users(id) on delete cascade, scan_id uuid not null references public.digital_scans(id) on delete cascade, device_id uuid not null references public.worker_devices(id), payload jsonb not null check(jsonb_typeof(payload)='array'), payload_sha256 text not null check(payload_sha256 ~ '^[a-f0-9]{64}$'), status text not null default 'proposed' check(status in ('proposed','approved','executing','complete','rejected','expired')), approved_at timestamptz, created_at timestamptz not null default now(), unique(scan_id,payload_sha256)
);
create table public.worker_action_manifests (
 id uuid primary key default gen_random_uuid(), plan_id uuid not null references public.digital_plans(id) on delete cascade, device_id uuid not null references public.worker_devices(id), payload jsonb not null, payload_sha256 text not null check(payload_sha256 ~ '^[a-f0-9]{64}$'), signature_b64 text not null, expires_at timestamptz not null, consumed_at timestamptz, execution_result jsonb, created_at timestamptz not null default now(), unique(device_id,payload_sha256), check(expires_at > created_at)
);
create table public.quarantine_items (
 id uuid primary key default gen_random_uuid(), user_id uuid not null references public.app_users(id) on delete cascade, device_id uuid not null references public.worker_devices(id), manifest_id uuid references public.worker_action_manifests(id), original_path_token text not null, quarantine_path_token text not null, sha256 text not null check(sha256 ~ '^[a-f0-9]{64}$'), quarantined_at timestamptz not null default now(), purge_after timestamptz not null default (now()+interval '30 days'), purged_at timestamptz, unique(device_id,quarantine_path_token), check(purge_after >= quarantined_at + interval '30 days')
);
create table public.archive_manifests (
 id uuid primary key default gen_random_uuid(), user_id uuid not null references public.app_users(id) on delete cascade, domain text not null, r2_key text not null unique, sha256 text not null check(sha256 ~ '^[a-f0-9]{64}$'), record_count bigint not null check(record_count>=0), min_recorded_at timestamptz, max_recorded_at timestamptz, schema_version integer not null check(schema_version>0), compression text not null check(compression in ('zstd','gzip')), verified_at timestamptz, created_at timestamptz not null default now()
);
create table public.backup_restore_drills (
 id uuid primary key default gen_random_uuid(), user_id uuid not null references public.app_users(id) on delete cascade, backup_key text not null, backup_sha256 text not null check(backup_sha256 ~ '^[a-f0-9]{64}$'), encrypted boolean not null default true, drill_status text not null default 'queued' check(drill_status in ('queued','running','passed','failed')), restored_at timestamptz, created_at timestamptz not null default now()
);
create table public.storage_forecasts (
 id uuid primary key default gen_random_uuid(), user_id uuid not null references public.app_users(id) on delete cascade, recorded_at timestamptz not null default now(), hot_bytes bigint not null check(hot_bytes >= 0), archive_bytes bigint not null check(archive_bytes >= 0), estimated_monthly_cost_usd numeric(12,4) not null check(estimated_monthly_cost_usd >= 0), methodology text not null
);
alter table public.worker_devices enable row level security; alter table public.worker_heartbeats enable row level security; alter table public.digital_scans enable row level security; alter table public.digital_inventory_items enable row level security; alter table public.digital_findings enable row level security; alter table public.digital_plans enable row level security; alter table public.worker_action_manifests enable row level security; alter table public.quarantine_items enable row level security; alter table public.archive_manifests enable row level security; alter table public.backup_restore_drills enable row level security; alter table public.storage_forecasts enable row level security;
create policy own_worker_devices on public.worker_devices using(user_id=auth.uid() and public.is_allowed_aal2()) with check(user_id=auth.uid() and public.is_allowed_aal2());
create policy own_worker_heartbeats on public.worker_heartbeats using(exists(select 1 from public.worker_devices d where d.id=device_id and d.user_id=auth.uid()) and public.is_allowed_aal2());
create policy own_digital_scans on public.digital_scans using(user_id=auth.uid() and public.is_allowed_aal2()) with check(user_id=auth.uid() and public.is_allowed_aal2());
create policy own_digital_inventory on public.digital_inventory_items using(user_id=auth.uid() and public.is_allowed_aal2()); create policy own_digital_findings on public.digital_findings using(user_id=auth.uid() and public.is_allowed_aal2()); create policy own_digital_plans on public.digital_plans using(user_id=auth.uid() and public.is_allowed_aal2()); create policy own_manifests on public.worker_action_manifests using(exists(select 1 from public.digital_plans p where p.id=plan_id and p.user_id=auth.uid()) and public.is_allowed_aal2()); create policy own_quarantine on public.quarantine_items using(user_id=auth.uid() and public.is_allowed_aal2()); create policy own_archives on public.archive_manifests using(user_id=auth.uid() and public.is_allowed_aal2()); create policy own_drills on public.backup_restore_drills using(user_id=auth.uid() and public.is_allowed_aal2());
create policy own_storage_forecasts on public.storage_forecasts using(user_id=auth.uid() and public.is_allowed_aal2());
grant select,insert,update on public.worker_devices,public.digital_scans,public.digital_plans to authenticated; grant select on public.worker_heartbeats,public.digital_inventory_items,public.digital_findings,public.worker_action_manifests,public.quarantine_items,public.archive_manifests,public.backup_restore_drills,public.storage_forecasts to authenticated;
create index worker_heartbeat_device_idx on public.worker_heartbeats(device_id,received_at desc); create index digital_scan_device_state_idx on public.digital_scans(device_id,status,created_at desc); create index inventory_scan_hash_idx on public.digital_inventory_items(scan_id,sha256) where sha256 is not null; create index quarantine_due_idx on public.quarantine_items(purge_after) where purged_at is null; create index storage_forecast_user_idx on public.storage_forecasts(user_id,recorded_at desc);
insert into public.workflow_definitions(manager_id,code,version,trigger_type,input_schema,output_schema,active) select managers.id, workflows.code,1,'manual_or_schedule','{}'::jsonb,'{}'::jsonb,true from public.managers cross join (values ('digital-estate-lightweight'),('digital-estate-deep-scan'),('digital-estate-archive-maintenance')) workflows(code) where managers.code='digital_estate' on conflict(code) do nothing;
