name: Edge functions
on: [pull_request, merge_group]

permissions:
  contents: read
jobs:
  deno:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: denoland/setup-deno@v2
      - run: deno fmt --check supabase/functions
      - run: deno lint --rules-exclude=no-import-prefix supabase/functions
      - run: deno check supabase/functions/*/index.ts
      - run: deno test supabase/functions/_shared/*_test.ts
